### ISSUE TITLE
attempt to index local 'sailrot' (a nil value) in init.lua:172

### ISSUE THREAD

**Issue by Bastrabun** [TheTermos/sailing_kit#6] opened 2020-12-21 19:09 UTC
Exact circumstances are unknown, I can't reproduce.

```
2020-12-21 19:51:11: ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod 'sailing_kit' in callback luaentity_Step(): /home/mtlive1/.minetest/mods/sailing_kit/init.lua:172: attempt to index local 'sailrot' (a nil value)
2020-12-21 19:51:11: ERROR[Main]: stack traceback:
2020-12-21 19:51:11: ERROR[Main]: 	/home/mtlive1/.minetest/mods/sailing_kit/init.lua:172: in function 'logic'
2020-12-21 19:51:11: ERROR[Main]: 	/home/mtlive1/.minetest/mods/mobkit/init.lua:958: in function 'func'
2020-12-21 19:51:11: ERROR[Main]: 	...inetest_live/bin/../builtin/profiler/instrumentation.lua:106: in function 'old_on_step'
2020-12-21 19:51:11: ERROR[Main]: 	/home/mtlive1/.minetest/mods/monitoring/builtin/on_step.lua:17: in function </home/mtlive1/.minetest/mods/monitoring/builtin/on_step.lua:15>
```

For my reference: 139

**Comment by TheTermos** [comment] 2020-12-29 17:50
Hmm, looks like the mast must have disappeared, or maybe got detached. Will investigate.

What MT version is it?

**Comment by Bastrabun** [comment] 2020-12-31 16:09
It's on a 5.3.0 server. If I can do anything to help debug, let me know. I can't reproduce 100%, but the issue happened twice already.

**Comment by TheTermos** [comment] 2021-01-01 14:42
Anyway, I can think of only one way this could go wrong, can you please try the dev version https://github.com/TheTermos/sailing_kit/archive/dev.zip and report back?

Looks like the attachment code is acting up in 5.3

**Comment by TheTermos** [comment] 2021-01-10 15:52
Merged. In case the problem isn't gone let me know and we'll reopen.

**Closed as completed by TheTermos** 2021-01-10 15:52 UTC
